# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87188f843a551b23af9712d9960d701f007a790fa401aa1f21a9a07d5dc7b92475edbb2423eac2f7c060659c8f666fe34d880b0ee611921d722a30208ef6cbed

test:
  secret_key_base: fec3a03aa6e8275cedbe05977b97afd982e89e11bba84307e049387411b5250b473a77788a59992c91246919f57466836daa04d6ab84ec65d37c85044f7d5851

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
